name: yutianc-data-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
 # Jupyter
  - jupyterlab
  - nodejs
  - notebook
  - tornado
  - nbconvert
  - widgetsnbextension
  - jupyter_contrib_nbextensions
#Python
  - python=3.7
  - ipywidgets
  - numpy
  - scipy
  - matplotlib
  - pandas
  - bokeh
  - plotly
  - rise
  - appmode
  - jieba
  - wordcloud
